### ISSUE TITLE
MQTT commands ignored

### ISSUE THREAD

**Issue by tube0013** [forkineye/ESPixelStick#148]
I'm trying to get mqtt support working within HomeAssistant.  I have it enable on the ESPixelStick:

<img width="580" alt="screen shot 2019-01-06 at 1 33 13 pm" src="https://user-images.githubusercontent.com/11084412/50740110-bed79e80-11b7-11e9-843c-2efcaba0fe42.png">

 and can see the status messages come across when it boots up:

```
pixelstick/stick1/light/status OFF
pixelstick/stick1/brightness/status 100
pixelstick/stick1/rgb/status 255,255,255
```

in HomeAssistant I have it set up per the instructions on the main page here, only difference is the changes since mqtt-json is depreciated now:

```
light:
  - platform: mqtt
    schema: json
    name: "PixelStick"
    state_topic: "pixelstick/stick1"
    command_topic: "pixelstick/stick1/set"
    brightness: true
    rgb: true
    effect: true
    effect_list:
      - Solid
      - Blink
      - Flash
      - Rainbow
      - Chase
      - Fire flicker
      - Lightning
      - Breathe
```
When I send commands I see them come out over mqtt but the ESPixelStick does not respond to them:

```
pixelstick/stick1/set {"state": "ON"}
pixelstick/stick1/set {"state": "ON"}
pixelstick/stick1/set {"state": "ON", "brightness": 255}
```

Is there any way to de-bug this?  Any other suggestion, or pointers?
